# EMA 信号监控配置示例
# 将以下配置添加到你的 config.yaml 文件中

# EMA 买入信号监控
ema_signal:
  enabled: true                    # 是否启用 EMA 监控
  short_period: 9                  # 短期 EMA 周期（默认9）
  long_period: 21                  # 长期 EMA 周期（默认21）
  timeframe: '15m'                 # 时间周期：'5m', '15m', '1h'
  volume_threshold: 1.5            # 成交量放大倍数阈值（默认1.5倍）

# 通知配置
notification:
  log: true                        # 日志通知（默认启用）
  file: true                       # 文件通知（默认启用）
  alert_file: 'signals/ema_alerts.txt'  # 信号保存文件路径

  email: false                     # 邮件通知（可选）
  email_config:
    smtp_server: 'smtp.gmail.com'
    smtp_port: 587
    sender: 'your_email@gmail.com'
    password: 'your_app_password'
    receivers:
      - 'receiver1@gmail.com'
      - 'receiver2@gmail.com'

  telegram: false                  # Telegram 通知（可选）
  telegram_config:
    bot_token: 'YOUR_BOT_TOKEN'
    chat_id: 'YOUR_CHAT_ID'
